export const FETCH_POST_BEGIN = "FETCH_POST_BEGIN";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";

export const FETCH_SINGLE_POST_BEGIN = "FETCH_SINGLE_POST_BEGIN";
export const FETCH_SINGLE_POST_SUCCESS = "FETCH_SINGLE_POST_SUCCESS";
export const FETCH_SINGLE_POST_FAILURE = "FETCH_SINGLE_POST_FAILURE";

export const POST_VOTE_SUCCESS = "POST_LIKE_SUCCESS";

export const ADD_NEW_COMMENT = "ADD_NEW_COMMENT";
export const NEW_COMMENT_COMPLETED = "NEW_COMMENT_COMPLETED";
export const ADD_COMMENT_FAILED = "ADD_COMMENT_FAILED";

export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";

export const USER_SIGNUP_BEGIN = "USER_SIGNUP_BEGIN";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";

export const USER_LOGIN_BEGIN = "USER_LOGIN_BEGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const LOGGED_IN = "LOGGED_IN";
